/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orutaprivacy;

import com.ecs.api.dropbox.Authorization;

import com.dropbox.core.DbxException;
import com.ecs.api.util.AppConfiguration;
import static com.ecs.api.util.AppConfiguration.CONF_APP_KEY;
import static com.ecs.api.util.AppConfiguration.CONF_APP_SECRET;
import static com.ecs.api.util.AppConfiguration.CONF_APP_AUTH;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author valla
 */
public class Authorizer extends javax.swing.JFrame {

    private Authorization authorize;
    private AppConfiguration appConfig;

    /**
     * Creates new form Authorizer
     */
    public Authorizer() {
        initComponents();
        appConfig = new AppConfiguration();
        if(!appConfig.loadConfiguration()){
            appConfig.createConf();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAppKey = new javax.swing.JTextField();
        txtAppSecret = new javax.swing.JTextField();
        btnURLGen = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtAuthCode = new javax.swing.JTextField();
        btnValidate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarURL = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnSaveAuth = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dropbox Authorization");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("DropBox Authorization");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Application Info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel2.setText("App Key");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel3.setText("App Secret");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 30));

        btnURLGen.setText("Authorize URL");
        btnURLGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnURLGenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAppSecret, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(txtAppKey))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnURLGen)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAppKey, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAppSecret, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnURLGen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "URL Authorization", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        btnValidate.setText("Validate Code");
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });

        txtarURL.setColumns(20);
        txtarURL.setRows(5);
        jScrollPane1.setViewportView(txtarURL);

        jLabel8.setText("Authorization Code");

        btnSaveAuth.setText("Save Auth");
        btnSaveAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAuthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAuthCode))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveAuth, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAuthCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValidate)
                    .addComponent(btnSaveAuth))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1)
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnURLGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnURLGenActionPerformed
        String appKey = txtAppKey.getText().trim();
        String appSecret = txtAppSecret.getText().trim();
        if (!appKey.isEmpty() && !appSecret.isEmpty()) {
            authorize = new Authorization(appKey, appSecret);

            // Storing App Values to Config
            Map<String, String> properties = new HashMap<>();
            properties.put(CONF_APP_KEY, appKey);
            properties.put(CONF_APP_SECRET, appSecret);
            appConfig.storeProperties(properties);

            txtarURL.setText(authorize.getAuthURL());
            lblStatus.setForeground(Color.blue);
            lblStatus.setText("Authorization URL generated Successfully!");
            /*try {
             authorize.generateAuthCode();
             } catch (IOException ex) {
             JOptionPane.showMessageDialog(rootPane, "Opening Brower and navigating URI failed... Please Validate URI Manually", "Failure", JOptionPane.INFORMATION_MESSAGE);
             }*/
        } else {
            JOptionPane.showMessageDialog(rootPane, "App Key and App Secret cannot be left Empty", "Enter Values", JOptionPane.ERROR_MESSAGE);
            lblStatus.setForeground(Color.RED);
            lblStatus.setText("App Key and App Secret cannot be left Empty!");
        }
    }//GEN-LAST:event_btnURLGenActionPerformed

    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
        String appAccessCode = txtAuthCode.getText().trim();
        if (!appAccessCode.isEmpty()) {
            try {
                authorize.authorize(appAccessCode);
                lblStatus.setForeground(Color.blue);
                lblStatus.setText("Access Code Validated Successfully!");
            } catch (DbxException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error in Validation", JOptionPane.ERROR_MESSAGE);
                lblStatus.setForeground(Color.RED);
                lblStatus.setText("Error in Validation!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "App Access Code cannot be left Empty", "Enter Access code", JOptionPane.ERROR_MESSAGE);
            lblStatus.setForeground(Color.RED);
            lblStatus.setText("App Access Code cannot be left Empty!");
        }
    }//GEN-LAST:event_btnValidateActionPerformed

    private void btnSaveAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAuthActionPerformed
        JFileChooser saveDialog = new JFileChooser();
        saveDialog.setDialogTitle("Specify a file to save");
        int value = saveDialog.showSaveDialog(rootPane);
        if (value == JFileChooser.APPROVE_OPTION) {
            File fileToSave = saveDialog.getSelectedFile();
            try {
                authorize.saveAuthInfo(fileToSave);

                // Storing Auth File Name
                Map<String, String> properties = new HashMap<>();
                properties.put(CONF_APP_AUTH, fileToSave.getAbsolutePath());                
                appConfig.storeProperties(properties);
                
                lblStatus.setForeground(Color.blue);
                lblStatus.setText("App Access Token Saved Successfully!");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, "App Access Token cannot be Saved", "Error Saving Access Token", JOptionPane.ERROR_MESSAGE);
                lblStatus.setForeground(Color.RED);
                lblStatus.setText("App Access Token cannot be Saved!");
            }
        } else if (value == JFileChooser.ERROR_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "App Access Token cannot be Saved", "Error Saving Access Token", JOptionPane.ERROR_MESSAGE);
            lblStatus.setForeground(Color.RED);
            lblStatus.setText("App Access Token cannot be Saved!");
        } else {
            //JOptionPane.showMessageDialog(rootPane, "App Access Token Save cancelled", "Error Saving Access Token", JOptionPane.ERROR_MESSAGE);
            lblStatus.setForeground(Color.RED);
            lblStatus.setText("App Access Token Save cancelled!");
        }
    }//GEN-LAST:event_btnSaveAuthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authorizer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authorizer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authorizer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authorizer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authorizer().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveAuth;
    private javax.swing.JButton btnURLGen;
    private javax.swing.JButton btnValidate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtAppKey;
    private javax.swing.JTextField txtAppSecret;
    private javax.swing.JTextField txtAuthCode;
    private javax.swing.JTextArea txtarURL;
    // End of variables declaration//GEN-END:variables
}
