/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package orutaprivacy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author RameshKumar
 */
public class regform extends javax.swing.JFrame {
  /*  Connection con;
    String url;
    String driver;
    String db;*/

    /**
     * Creates new form regform
     */
    public regform() {
        initComponents();
        getcomb();
    }
    
    private void getcomb()
    {
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/orutapreserving","root","");
           java.sql.Statement st = con.createStatement();
           String sql="select * from formreg";
           ResultSet rs = st.executeQuery(sql);
           while(rs.next())
           {
               String owner=rs.getString("Username");
               owner_combo.addItem(owner);
              //owner_combo.add(rs.getString(Username);
           }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pno_txt = new javax.swing.JTextField();
        fname_txt = new javax.swing.JTextField();
        lname_txt = new javax.swing.JTextField();
        uname_txt = new javax.swing.JTextField();
        pass_txt = new javax.swing.JTextField();
        bdate_txt = new javax.swing.JTextField();
        gender_txt = new javax.swing.JTextField();
        city_txt = new javax.swing.JTextField();
        owner_combo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        backgroundimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 23)); // NOI18N
        jLabel2.setForeground(java.awt.Color.yellow);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create your Cloud Account");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 680, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.yellow);
        jLabel1.setText("Gender");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.yellow);
        jLabel3.setText("Firstname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 70, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.yellow);
        jLabel4.setText("Lastname");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 70, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.yellow);
        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.yellow);
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 70, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.yellow);
        jLabel7.setText("Birthdate");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 70, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.yellow);
        jLabel8.setText("Phoneno");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 70, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.yellow);
        jLabel9.setText("City");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 70, -1));

        pno_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pno_txtActionPerformed(evt);
            }
        });
        getContentPane().add(pno_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 150, 30));

        fname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fname_txtActionPerformed(evt);
            }
        });
        getContentPane().add(fname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 150, 30));
        getContentPane().add(lname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 150, 30));

        uname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uname_txtActionPerformed(evt);
            }
        });
        getContentPane().add(uname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 150, 30));
        getContentPane().add(pass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 150, 30));

        bdate_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdate_txtActionPerformed(evt);
            }
        });
        getContentPane().add(bdate_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 150, 30));

        gender_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_txtActionPerformed(evt);
            }
        });
        getContentPane().add(gender_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 150, 30));

        city_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city_txtActionPerformed(evt);
            }
        });
        getContentPane().add(city_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 150, 30));

        owner_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                owner_comboMouseExited(evt);
            }
        });
        getContentPane().add(owner_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 120, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, 20));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, 20));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 80, 20));

        backgroundimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/7.jpg"))); // NOI18N
        getContentPane().add(backgroundimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bdate_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdate_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdate_txtActionPerformed

    private void fname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fname_txtActionPerformed

    private void gender_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender_txtActionPerformed

    private void pno_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pno_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pno_txtActionPerformed

    private void city_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_city_txtActionPerformed

    private void uname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uname_txtActionPerformed

    private void owner_comboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_owner_comboMouseExited
        /*String uname=owner_combo.getSelectedItem().toString();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/orutapreserving","root","");
        PreparedStatement pst=conn.prepareStatement("select *from formreg where Username='"+uname+"'");
        ResultSet rst=pst.executeQuery();
        if(rst.next())
        {
            String groupkey=rst.getString("groupkey");
            gkey_txt.setText(groupkey);
            
        }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_owner_comboMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new index().setVisible(true);
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try
        {
          Connection  con=null;
          String  url="jdbc:mysql://localhost:3306/";
           String driver="com.mysql.jdbc.Driver";
           String db="orutapreserving";
            String Firstname = fname_txt.getText();
            String Lastname = lname_txt.getText();
            String Username = uname_txt.getText();
            String Password = pass_txt.getText();
            String Birthdate = bdate_txt.getText();
            String Gender = gender_txt.getText();
            String City=city_txt.getText();
            String Phoneno = pno_txt.getText();
            //String grpkey = gkey_txt.getText();
            String owner=owner_combo.getSelectedItem().toString();
            Class.forName(driver);
            con=(Connection)DriverManager.getConnection(url+db, "root","");
            java.sql.Statement st = con.createStatement();
            String sql1="select count(Ownername) from userreg where Ownername='"+owner+"'";
           
           ResultSet rst=st.executeQuery(sql1);
            rst.next();
            int rowcount=rst.getInt(1);
                System.out.println(rowcount+"count owner");
            if(rowcount<=9)
            {
            java.sql.Statement st1 = con.createStatement();
            String sql =  "INSERT INTO `userreg`(`Firstname`,`Lastname`,`Ownername`,`Username`,`Password`,`Birthdate`,`Gender`,`City`,`Phoneno`) VALUES ('"+Firstname+"','"+Lastname+"','"+owner+"','"+Username+"','"+Password+"','"+Birthdate+"','"+Gender+"','"+City+"','"+Phoneno+"')";
            //System.out.println(sql);
            st1.executeUpdate(sql);
            System.out.println("value inserted");
             new index().setVisible(true); 
            dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"this data owner allready registered 10 user please choose another owner");
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      fname_txt.setText("");
     lname_txt.setText("");
     uname_txt.setText("");
     pass_txt.setText("");
     bdate_txt.setText("");
     gender_txt.setText("");
     city_txt.setText("");
     pno_txt.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regform().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundimg;
    private javax.swing.JTextField bdate_txt;
    private javax.swing.JTextField city_txt;
    private javax.swing.JTextField fname_txt;
    private javax.swing.JTextField gender_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname_txt;
    private javax.swing.JComboBox owner_combo;
    private javax.swing.JTextField pass_txt;
    private javax.swing.JTextField pno_txt;
    private javax.swing.JTextField uname_txt;
    // End of variables declaration//GEN-END:variables
}
